import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Progressbar from "@/components/layouts/Progressbar"
import Header from "@/components/layouts/Header"

const FontFamily = Inter({ subsets: ['latin'],weight:'400' })

export const metadata: Metadata = {
  title: 'Create Ne',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={FontFamily.className}>
      <Header/>
      <Progressbar/>
        {children}
        </body>
    </html>
  )
}
